tiredofit/docker-db-backup

install/etc/s6/services/10-db-backup/run
Whenever I run the backup I see these two lines at the top of my log:
```
./run: line 5: [: !=: unary operator expected
./run: line 40: [: =: unary operator expected
```
I fixed this by wrapping the variables in quotes (as seen here: https://stackoverflow.com/questions/408975/compare-integer-in-bash-unary-operator-expected)
I also mentioned adding the port argument to influx in another issue (#5) and the fix that was applied is actually wrong.. I guess this verison of the influx cli takes the port as part of the `-host` argument. To keep the software config the same between database types I just made it append the port to the host in the `-host` argument.
This should fix influx backup and remove those two errors from the log.
=> Fix influx args as well as some errors in the log

Dockerfile, install/etc/s6/services/10-db-backup/run
- The couchdb backup endpoint was wrong (missing underscores in URL)
- The ENABLE_ZABBIX was set to TRUE from the base image, which will cause some errors get logged (not a big deal)
=> Fix couchdb backup endpoint; Set ENABLE_ZABBIX to FALSE by default

install/etc/s6/services/10-db-backup/run
the original wasn’t working for me. seemed to be some weird issues with the single quotes, and resulted in authentication errors.
this version uses the MYSQL_PWD env variable that the mysql and mysqldump programs look for.
this has been tested on my docker images
=> changed mysql password to env variable

Dockerfile, install/etc/services.available/10-db-backup/run
* Make DB_USER and DB_PASS optional for MongoDB
* Make DB_PASS optional for MySQL, PGSQL and Redis
* Update the alpine testing repo URI to `https://dl-cdn.alpinelinux.org/alpine/edge/testing` since `http://nl.alpinelinux.org/alpine/edge/testing` gives random DNS error.
=> #42 Make DB_USER and DB_PASS optional for some dbtypes; update alpine repo URI

README.md
It seems like the wrong image was linked. This commit fixes this.
=> Fix Docker image name and URL

install/etc/services.available/10-db-backup/run
The variable `target_time` was not being set when `DB_DUMP_BEGIN` was a relative time (i.e., it is a +XXX value).
Everything was working, but there was an ugly log message
```
2021-12-13-20:46:28 [NOTICE] ** [db-backup] Next Backup at                                                                              
date: invalid date '@'                                                                                                                  
```
The solution was to simply set the `target_time` variable in that branch of the if.
=> Fixing the print_notice for Next Backup when `DB_DUMP_BEGIN` is +XXX

install/etc/services.available/10-db-backup/run
The proper way to use MINIO or other S3-compatible object stores is by using the `--endpoint-url` parameter on the `aws` CLI.
All the configuration was well defined and prepared, but the `S3_HOST` environment variable was not used and thus MINIO users were not able to use this container. With this PR, that should be addressed.
I am myself a MINIO user and, after the proposed modifications, I was able to use this.
=> MINIO support by reacting to S3_HOST

README.md, install/etc/services.available/10-db-backup/run
Currently S3 region is hard-coded in the code to `ap-northeast-2`. In our case we are using Oracle cloud infrastructure S3 compatible API. When this region is selected our uploads fail due to the non-existing region.
This PR introduces ability for an end user to specify in which region S3 bucket resides. When we attached to the container, we tried to override the ENV variable `AWS_DEFAULT_REGION` to our Oracle's region and the upload was successful.
=> Provide region when using S3

install/etc/services.available/10-db-backup/run
Hi,
thanks for this really nice and comprehensive project!
When running this container as a Kubernetes cronjob, it is really inconvenient that the script exits with return code "1", thereby marking the job as a failure.
Instead, the script should return "0" because everything was successful.
=> Use exit code 0 when running in manual mode

README.md, install/etc/services.available/10-db-backup/run
Hi,
thanks again for this nice project.
While setting up backups in my environment I struggled with several inconsistencies and thought I would address them in this PR.
* S3_URI_STYLE is not used anywhere (anymore)
* BACKUP_TYPE is not documented anywhere, redundant with BACKUP_LOCATION
* S3_HOST is not used anymore, document S3_ENDPOINT instead
ref https://github.com/tiredofit/docker-db-backup/commit/4d6419fd184590c3620a7a9a5e70ef3adecb97ee
=> Correct several variables for S3 backups

README.md, install/etc/services.available/10-db-backup/run
Hi, it's me again!
I wanted to update to the latest tag today, but it turns out that I actually messed up my last PR - sorry about that.
S3_ENDPOINT is not used anywhere in the code, but S3_HOST.
Fixes https://github.com/tiredofit/docker-db-backup/issues/89
=> Fix S3 variables (again)

install/assets/functions/10-db-backup
When running backup-now got error in log:
`
date: invalid date 'PRE pritunl.x-coding.pl/'
/assets/functions/10-db-backup: line 449: [: !=: unary operator expected
`
Not sure from where got 1st one, but 2nd is fixed by that.
=> Unary operator fix

install/usr/local/bin/restore
Fixes the variable name used to check which option was selected during port selection in interactive restore. Since the variable was empty, the port was not read from any source (environment variable or interactive input).
I looked a little further in the version history and, as far as I can see, the 3.3.5 update introduced the issue, even though the changelog claims to actually fix the issue : https://github.com/tiredofit/docker-db-backup/compare/3.3.4...3.3.5, so maybe I'm just missing something and this PR isn't actually needed.
=> Fix reading port number in interactive restore

install/assets/functions/10-db-backup
Post script support expects a value from a declared variable `$FILESIZE` to provide the size of the backup files. Such a variable does not exist, leading to a situation where using `"${9}"` in a custom script furnishes the checksum hash. However, earlier up in the script the file size of the backup is indeed assigned to a variable, only that is it completely in lower case: `$filesize`. This commit aims to fix that inconsistency.
=> Fix incorrect case for filesize variable

README.md, install/assets/functions/10-db-backup
This adds the option `GZ_RSYNCABLE` for gzip compression. Rsync and Duplicati transfers/backupss of large archives are much faster when this option is used.
=> Add --rsyncable for gzip compression

Dockerfile
Update influxdb client to 2.4.0.
Scanning the current latest image of db-backup shows a number of CVEs associated with the installed 2.2.1 version of /usr/sbin/influx. PR updates the client to the latest 2.4.0. 
```
usr/sbin/influx (gobinary)
Total: 5 (MEDIUM: 1, HIGH: 4, CRITICAL: 0)
┌─────────────────────┬────────────────┬──────────┬────────────────────────────────────┬───────────────────────────────────┬─────────────────────────────────────────────────────────────┐
│       Library       │ Vulnerability  │ Severity │         Installed Version          │           Fixed Version           │                            Title                            │
├─────────────────────┼────────────────┼──────────┼────────────────────────────────────┼───────────────────────────────────┼──────────────── …
```
=> Update Dockerfile to use influxdb client 2.4.0

install/assets/functions/10-db-backup
This change removes an extra linebreak that causes a non-stop log of errors like this (from #201):
```
s6-supervise 99-run_forever (child): fatal: unable to exec run: Exec format error
s6-supervise 99-run_forever: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise 99-run_forever (child): fatal: unable to exec run: Exec format error
s6-supervise 99-run_forever: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise 99-run_forever (child): fatal: unable to exec run: Exec format error
s6-supervise 99-run_forever: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise 99-run_forever (child): fatal: unable to exec run: Exec format error
s6-supervise 99-run_forever: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise 99-run_forever (child): fatal: …
```
=> Fix issue #201 - 99-run_forever exec format error

install/assets/functions/10-db-backup
The [`pg_isready` documentation](https://www.postgresql.org/docs/current/app-pg-isready.html) says that
> It is not necessary to supply correct user name, password, or database name values to obtain the server status; however, if incorrect values are provided, the server will log a failed connection attempt.
E.g.,
```
/ # pg_isready --dbname=thisdbdoesnotexist --host=${DB_HOST} --port=${DB_PORT} --username=thisuserdoesnotexist
postgres: - accepting connections
```
As a result, when we set `DB_NAME` to `ALL`, calls to the `check_availability` function (which uses `pg_isready`) cause the server to log the following error:
```
FATAL:  database "ALL" does not exist
```
To eliminate this error, this change simplifies the `pg_isready` call.
=> Simplify pg_isready usage

install/assets/functions/10-db-backup
Fixes #215 , at least for SQLite.
I fixed what looks like similar code mistakes for InfluxDB and MSSQL, but don't have a way to test those.
=> Set ltargets properly

Dockerfile, install/assets/functions/10-db-backup
Capture the exit code of the `aws s3` and `blobxfer` command and reuse `check_exit_code` function to report errors occur in the `move_dbbackup` function. 
Also add `zip` package to the image to be used in post backup script.
=> #199 Report error when move the backup file to S3 or Blob fails

install/assets/functions/10-db-backup
Removed the flag so there is no `use` in the dump file
Fixes: #249
=> Remove the --database flag for a single db dump

install/usr/local/bin/restore
Fix https://github.com/tiredofit/docker-db-backup/issues/136
The filenames display by the `restore` command are not sorted
```
...
279) /backups/today/mongo_my_project_mongo_20231010-223817.archive.gz
280) /backups/today/mongo_my_project_mongo_20231011-052321.archive.gz
281) /backups/today/mongo_my_project_mongo_20231010-231817.archive.gz
282) /backups/today/mongo_my_project_mongo_20231011-084822.archive.gz
283) /backups/today/mongo_my_project_mongo_20231010-224817.archive.gz
284) /backups/today/mongo_my_project_mongo_20231011-190827.archive.gz
285) /backups/today/mongo_my_project_mongo_20231011-060821.archive.gz
286) /backups/today/mongo_my_project_mongo_20231010-220817.archive.gz
287) /backups/today/mongo_my_project_mongo_20231011-061321.archive.gz
288) …
```
=> Sort filenames alphabetically when using the restore command

install/usr/local/bin/restore
This should fix https://github.com/tiredofit/docker-db-backup/issues/112
When an authentication database is specified in `DB_AUTH`, it's used for the backup but not for the restore.
From the [mongorestore documentation](https://www.mongodb.com/docs/database-tools/mongorestore/#std-option-mongorestore.--authenticationDatabase):
> --authenticationDatabase=<dbname>
> Specifies the authentication database where the specified --username has been created.
Without this option, when the user is in the `admin` authentication database, this error occurs:
```
2023-10-11T23:02:59.017+0200 error connecting to host: could not connect to server: connection() error occurred during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": …
```
=> Use authentification database in mongorestore

install/etc/services.available/10-db-backup/run
Based on the issue #214 I propose a solution to use DB_DUMP_BEGIN as a base time to run like a cronjob.
If the DB_DUMP_BEGIN is specified in hh:mm:ss format, then the system uses it as a base time with DB_DUMP_FREQ as the recursion.
I'm open to comments about this solutions.
=> Adds a cronjob-like mechanism

install/assets/functions/10-db-backup
the config file is referenced by -C , not -c
=> Update 10-db-backup msmtp -C

Dockerfile
In this PR,
* Update AWS CLi to `1.31.5`
* Use pip3 to install awscli
=> #298 Use pip to install awscli to remove the deprecation warning

examples/compose.yml, examples/mssql-blobxfer/compose.yml, examples/mssql/compose.yml
When deploying the image, I noticed that the backup interval was not respected. I configured the image according to the examples. I noticed that the variable names in the examples and documentation are different. DEFAULT_DUMP_INTERVAL should be renamed to DEFAULT_BACKUP_INTERVAL. DEFAULT_DUMP_BEGIN should be renamed into DEFAULT_BACKUP_BEGIN
=> Fix environment variables in examples

README.md
According to the code, the format for `DEFAULT_CREATE_LATEST_SYMLINK` contains underscores between type, name and host (not dashes)
https://github.com/tiredofit/docker-db-backup/blob/a5b15b441246da0dea563fd4b150621fc7e358e7/install/assets/functions/10-db-backup#L1645
=> [Docs] Updated `DEFAULT_CREATE_LATEST_SYMLINK` description format

README.md
Code uses `DEFAULT_BLOBXFER_MODE` but docs denote `DEFAULT_BLOBXFER_REMOTE_MODE`.
=> [docs] fixed blobxfer mode correct parameter name

install/usr/local/bin/restore
- Switch the mysql command to mariadb to resolve the deprecation warning.
- Fix the restore issue caused by missing SSL configuration (error message: "TLS/SSL error: SSL is required, but the server does not support it").
=> Update restore script

install/usr/local/bin/restore
mongoDB restore always dropped schema, irrespective of flag variant, due to wildcard being the first option in case.
=> fix: wildcard case order
