- install/etc/s6/services/10-db-backup/run
> Issue 2: Fixing typo which was causing the script to fail.

- install/etc/s6/services/10-db-backup/run
I realized that you can't backup a redis which is protected by a password.
I added the -a option for the redis-cli.
I did the changes in the same manner (REDIS_PASS_STR).
> chg: added AUTH for redis

- README.md
I found no DB_SERVER environment variable.
Is DB_HOST correct?
> changed DB_SERVER into DB_HOST

- install/etc/s6/services/10-db-backup/run
Small fix.
I have balancer (HAProxy) on different port and want backup through it
> Allow override MYSQL DB_PORT

- install/etc/s6/services/10-db-backup/run
> Fix usage of DB_PORT for single mariadb database

- install/etc/services.available/10-db-backup/run
This fixes the issue I ran into here: https://github.com/tiredofit/docker-db-backup/issues/39#issuecomment-684068219.
> Fix POST_SCRIPT Environment Vairable Run

- README.md
- install/etc/services.available/10-db-backup/run
* #44 Remove 'invalid date' error message when performing backup-now
* #42 Update README
> Fix backup now date error message

- install/etc/services.available/10-db-backup/run
Fixes #46 
Confirmed fix with Postgres 11 and MariaDB 10.
> Fix Docker Secrets injection from DB_USER_FILE/DB_PASS_FILE

- install/etc/services.available/10-db-backup/run
> #51 Fix backup of multiple InfluxDB databases failure

- install/etc/services.available/10-db-backup/run
Case statement is missing double semi-colon.
> Fix syntax error - Issue #69

- install/usr/local/bin/restore
As well as fixing a few issues I came across when trying to run the script. Split into commits so you can cherry-pick what parts you want to keep.
> Add Mongo support to restore script

- install/usr/local/bin/restore
Fixed a typo when restoring Postgres db.
> Fix postgres restore wrong db type

- README.md
> updated README with correct custom scripts directory

- README.md
> updated README with missing DB_DUMP_TARGET environment variable

- CHANGELOG.md
Add clear migration instructions for custom script paths
> Improve release notes for 3.4.1

- README.md
> Add blobxfer documentation in readme file.

- README.md
- install/assets/functions/10-db-backup
> Bugfix: S3 database cleanups

- install/assets/functions/10-db-backup
> Removed EXTRA_OPTS in MySQL status check

- .github/workflows/main.yml
- .github/workflows/manual.yml
- Dockerfile
> Add cargo to build dependencies

- install/assets/functions/10-db-backup
Update the name since blobxfer is not writing to s3
> Updated name where it is not writing to s3

- CHANGELOG.md
- README.md
- install/assets/functions/10-db-backup
In this PR:
1. Added an option DB_AUTH for PGSQL
2. Fixed lint issues and typos in README files
> fix: Add an option DB_AUTH for PGSQL

- install/assets/functions/10-db-backup
> add postgres globals backup if SPLIT_DB=true

- install/assets/functions/10-db-backup
> feat(235) Synchronize local storage from S3 before upload

- install/assets/functions/10-db-backup
> warn instead of warning

- install/assets/functions/10-db-backup
Fix for https://github.com/tiredofit/docker-db-backup/issues/417
> fix: exitcode masking db errors

- install/assets/functions/10-db-backup
> #420: Fix the change of `exit_code` to `exitcode`
